### PR TITLE
0.1.0

### LINKED ISSUE #8: 3D support
Add (validate) support for 3D systems. Should work already, I just haven't tested.
Maybe do some optimisation to ensure it works in a reasonable time.
Will also be useful with #7 implemented, as the runtime will be long

### LINKED ISSUE #27: Periodic boundary condition

### PR DESCRIPTION
**Pull request by viljarjf**
- Auto-generated docs with Sphinx, available at https://viljarjf.github.io/QM_sim/
- Refactors, move temporal solvers and Hamiltonian class
- Add GPU support with PyTorch as an optional dependency
- Adds plots
- Adds tqdm to temporal solvers
- WIP non-isotropic effective mass

Passes all examples and tests, except the solver comparison with C++-based solvers. 
C++ compilation is removed (commented out in the CMakeLists file), but the files are not removed in case they become useful later. 

Update:
Verified that 3D actually works. Added hydrogen atom example. 
Bumped to version 0.1.0 instead, as this really is a major update

Fix #27 
Fix #8

### CODE REVIEW

**Comment by henrtk** [comment]
Give me at least until the end of May and I may have time to look at it ;)

**Comment by viljarjf** [comment]
Might be an issue with docs generation with a clean environment, I think matplotlib needs to be added to the required modules

**Comment by viljarjf** [comment]
And the example code for spatial derivatives has been mangled

**Comment by viljarjf** [comment]
Implements #27 
Implements #8

**Pull request merged**
